---
kind: pipeline
name: default
trigger:
  event: ['pull_request']

steps:
  - name: setup
    image: node:16-alpine
    when:
      event: [pull_request]
    commands:
      - yarn install

  - name: lint
    image: node:16-alpine
    when:
      event: [pull_request]
    depends_on:
      - setup
    commands:
      - yarn lint

  - name: build
    image: node:16-alpine
    when:
      event: [pull_request]
    depends_on:
      - setup
    commands:
      - yarn build

---
kind: signature
hmac: 613da72197a259190d0c69bf3cdeed61356c02690908e647836fc42b274010fe

...
