---
kind: pipeline
type: docker
name: default
trigger:
  event: ['pull_request']

steps:
  - name: setup
    image: node:18-alpine
    when:
      event: [pull_request]
    commands:
      - yarn install

  - name: lint
    image: node:18-alpine
    when:
      event: [pull_request]
    depends_on:
      - setup
    commands:
      - yarn lint

  - name: build
    image: node:18-alpine
    when:
      event: [pull_request]
    depends_on:
      - setup
    environment:
      NEXT_PUBLIC_SANITY_PROJECT_ID:
        from_secret: sanity_project_id
      NEXT_PUBLIC_SANITY_DATASET:
        from_secret: sanity_dataset
    commands:
      - yarn build

---
kind: signature
hmac: b6ede7337f496e4f82c9a42d9e5d53d43bd2b2b3f92ecf6e7d1030fd4936d349

...
