---
kind: pipeline
type: docker
name: default
trigger:
  event: ['pull_request']

steps:
  - name: setup
    image: node:18-alpine
    when:
      event: [pull_request]
    commands:
      - yarn install

  - name: lint
    image: node:18-alpine
    when:
      event: [pull_request]
    depends_on:
      - setup
    commands:
      - yarn lint

  - name: build
    image: node:18-alpine
    when:
      event: [pull_request]
    depends_on:
      - setup
    commands:
      - yarn build

---
kind: signature
hmac: 6e33564faab634d9ae80902e4e913056eeb839d0ba1e3b731ccc11f3f524d5a7

...
