language: node_js
node_js:
  - "6"

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphicsmagick

services:
  - mongodb

notifications:
  webhooks: http://chewie.abakus.no/api/travis
